version: 0.0
os: ubuntu
files:
  - source: /
    destination: /opt/data/www/test.nirvanaxp.com/admin/aptest/
hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: root
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: root
      timeout: 60