version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html/
 
 
hooks:
  BeforeInstall:
    - location: service apache2 stop
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: service apache2 stop
      timeout: 300
      runas: ubuntu
